### ISSUE TITLE
Does it work on Mac or just on Windows?

### ISSUE THREAD

**Issue by Lumen750** [lmueller27/Fusion360PatternsAndTextures#5]
Hi

I have added the Add-in into the appropriate Add-in folder on my Mac, but it does not appear in Fusion 360, even after restarting the software. Does it only work on windows?

**Comment by lmueller27** [comment]
Hi, the Add-In should work both on Windows and Mac. 

Have you started the Add-In after installing it? Once you have added the Add-In to your \API\AddIns folder you need to:

1. In the toolbar, go to UTILITIES > Scripts and Add-Ins.
2. Run the Add-In from the list.

Afterwards, it should appear in the Mesh > Modify section.

**Comment by Lumen750** [comment]
Thanks for your response.

I realised that I made a typo in the name of the enclosing folder so that the folder name and the add-in name did not match.

It works now.
