### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by xArashii19** [lmueller27/Fusion360PatternsAndTextures#7]
I did all the steps you mentioned, as the other user mentioned too, I can't see either the right tool under the mesh, modify section, please provide a solution for this, thanks

**Comment by stefansjs** [comment]
I am having the same problem. I cloned the repository into the API/AddIns directory and Fusion does not seem to load it at all. I cannot see the addin from the Utilities -> AddIns menu.

**Comment by stefansjs** [comment]
Oh, I see. I had to rename the directory from "Fusion360PatternsAndTextures" to "Noise, Patterns and Textures". Then Fusion360 would find the plugin.

**Comment by lmueller27** [comment]
@stefansjs Thanks for the Update! Yeah, this is described in the manual: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/How-to-install-an-ADD-IN-and-Script-in-Fusion-360.html.

But I can see how this can be confusing. I will add it to the description. Thank you!
